server:
  port: 8081
  servlet:
    context-path: /easyprice
spring:
  datasource:
    url: jdbc:mysql://111.231.232.212:3306/shop?characterEncoding=UTF-8&autoReconnect=true
    password: mysqlroot
    username: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    call-setters-on-nulls: true
  mapper-locations: classpath*:mapper/*.xml



