server:
  port: 8081
  servlet:
    context-path: /easyprice
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiaochengxu?characterEncoding=UTF-8&autoReconnect=true
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    call-setters-on-nulls: true
  mapper-locations: classpath*:mapper/*.xml



